{{- if and .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "hello-world.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: "hello-world"
spec:
  gateways:
  {{- range .Values.istio.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
      - destination:
          port:
            number: 80
          host: {{ include "hello-world.fullname" . }}.{{ default .Release.Namespace }}.svc.cluster.local
{{- end }}
